### ISSUE TITLE
API: Sorting Things by name etc

### ISSUE THREAD

**Issue by eins78** [leihs/leihs-procure#23]
- [x] `buildings`: `name`, 'general' first!
- [x] `rooms`: `name`, 'general' first!
- [x] `users`: `firstname||lastname||login||id`
- [x] `main_categories`: `name`
- [x] `categories`: `name`
- [x] `budget_periods`: `end_date`
- [x] `budget_limits`: `budget_period .end_date`
- [x] `admins`: like users
- [x] `category_inspectors `: like users
- [x] `category_viewers`: like users
- [x] `organizations`: `name`
- [x] `templates`: `name`
- [x] ??? `requests`: `article_name||model.name`

(`||` means concat, like in SQL)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs-procure/pull/30

**Comment by nimaai** [comment]
`templates.name` does not exists (yet) so we sort as with requests: `article_name || model.name`.
